# version: '3.9'

services:
  nextjs:
    build: ./
    command: npm run dev
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
