# version: '3.9'

services:
  nextjs:
    build: ./
    command: npm run dev
    ports:
      - ${NEXT_PUBLIC_FRONTEND_PORT}:${NEXT_PUBLIC_FRONTEND_PORT}
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
